// Private Journeys 사전 상담 페이지 문구 (한/영)
export const journeysCopy = {
  ko: {
    eyebrow: 'PRIVATE JOURNEYS · 사전 상담',
    title: '당신만을 위한 한국 여행을\n함께 설계합니다.',
    intro: '커플, 가족, 친구와 함께하는 맞춤 여행. 공항 영접부터 전담 가이드, 차량, 레스토랑과 숙소까지 일정에 맞춰 준비합니다. 정식 오픈 전, 사전 상담 고객께 먼저 제안서를 보내드립니다.',
    points: ['담당 플래너가 직접 회신', '일정·예산에 맞춘 제안서', '공항 의전과 차량 연계'],
    sections: { you: '연락처', trip: '여행 정보', prefs: '관심사', message: '요청 사항' },
    fields: {
      name: '이름',
      email: '이메일',
      phone: '전화 / WhatsApp',
      country: '거주 국가',
      arrival: '도착 예정일',
      departure: '출발 예정일',
      flexible: '날짜는 조정 가능해요',
      adults: '성인',
      children: '아동',
      styles: '여행 스타일 (복수 선택)',
      places: '관심 지역 (복수 선택)',
      needs: '필요한 서비스 (복수 선택)',
      budget: '1인 예산 (항공권 제외)',
      contact: '선호하는 연락 방법',
      message: '원하시는 여행을 자유롭게 적어 주세요',
      messagePlaceholder: '예: 결혼기념일 여행이라 조용한 레스토랑과 궁궐 투어를 원해요.',
      optional: '선택',
    },
    styles: { culture: '역사·문화', food: '미식·다이닝', shopping: '쇼핑', nature: '자연·풍경', wellness: '웰니스·스파', kculture: 'K-컬처', family: '가족 여행', occasion: '기념일·특별한 날' },
    places: { seoul: '서울', jeju: '제주', busan: '부산', gyeongju: '경주', gangwon: '강원', unsure: '추천받고 싶어요' },
    needs: { airport: '공항 의전', chauffeur: '전용 차량', hotel: '호텔 예약', guide: '전담 가이드', dining: '레스토랑 예약', interpreter: '통역' },
    budgets: { b1: '400만 원 미만', b2: '400만 ~ 800만 원', b3: '800만 ~ 1,300만 원', b4: '1,300만 원 이상', unsure: '아직 모르겠어요' },
    contacts: { email: '이메일', whatsapp: 'WhatsApp', phone: '전화' },
    consentLabel: '[필수] 개인정보 수집·이용에 동의합니다.',
    consentDetail: '수집 항목: 이름, 이메일, 연락처, 거주 국가, 여행 일정·인원·관심사 · 이용 목적: 맞춤 여행 상담 및 제안서 발송 · 보유 기간: 상담 종료 후 1년 · 동의를 거부할 수 있으나, 거부 시 상담 신청이 제한됩니다.',
    privacyLink: '개인정보처리방침',
    submit: '사전 상담 신청',
    sending: '보내는 중…',
    required: '이름과 이메일을 입력하고 개인정보 수집·이용에 동의해 주세요.',
    error: '전송하지 못했습니다. 잠시 후 다시 시도하시거나 이메일·WhatsApp으로 연락해 주세요.',
    tooMany: '짧은 시간에 너무 많이 보내셨습니다. 잠시 후 다시 시도해 주세요.',
    sentTitle: '상담 신청이 접수되었습니다',
    sentBody: '담당 플래너가 확인 후 연락드리겠습니다. 급한 문의는 WhatsApp으로 주세요.',
    reference: '접수 번호',
    another: '다른 문의 남기기',
    airportCta: '공항 의전은 지금 바로 예약할 수 있어요',
  },
  en: {
    eyebrow: 'PRIVATE JOURNEYS · EARLY ENQUIRIES',
    title: 'Korea, designed\naround you.',
    intro: 'Tailor-made trips for couples, families and friends — from your welcome at the gate to private guides, chauffeurs, dining and stays. Before our official launch, early enquiries receive a proposal first.',
    points: ['A planner replies personally', 'A proposal built on your dates and budget', 'Seamless airport VIP and chauffeur'],
    sections: { you: 'About you', trip: 'Your trip', prefs: 'What you love', message: 'Anything else' },
    fields: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone / WhatsApp',
      country: 'Country of residence',
      arrival: 'Arrival date',
      departure: 'Departure date',
      flexible: 'My dates are flexible',
      adults: 'Adults',
      children: 'Children',
      styles: 'Travel style (choose any)',
      places: 'Destinations (choose any)',
      needs: 'Services you need (choose any)',
      budget: 'Budget per person (excl. flights)',
      contact: 'Preferred contact',
      message: 'Tell us about the trip you have in mind',
      messagePlaceholder: 'e.g. Our anniversary — quiet restaurants and a private palace tour.',
      optional: 'optional',
    },
    styles: { culture: 'History & culture', food: 'Food & dining', shopping: 'Shopping', nature: 'Nature & scenery', wellness: 'Wellness & spa', kculture: 'K-culture', family: 'Family trip', occasion: 'Special occasion' },
    places: { seoul: 'Seoul', jeju: 'Jeju', busan: 'Busan', gyeongju: 'Gyeongju', gangwon: 'Gangwon', unsure: 'Recommend for me' },
    needs: { airport: 'Airport VIP', chauffeur: 'Private chauffeur', hotel: 'Hotel booking', guide: 'Private guide', dining: 'Restaurant bookings', interpreter: 'Interpreter' },
    budgets: { b1: 'Under USD 3,000', b2: 'USD 3,000 – 6,000', b3: 'USD 6,000 – 10,000', b4: 'USD 10,000+', unsure: 'Not sure yet' },
    contacts: { email: 'Email', whatsapp: 'WhatsApp', phone: 'Phone' },
    consentLabel: '[Required] I agree to the collection and use of my personal data.',
    consentDetail: 'Data: name, email, phone, country, trip dates, party size and interests · Purpose: travel consultation and sending a proposal · Retention: 1 year after the consultation ends · You may decline, but we cannot respond to the enquiry without it.',
    privacyLink: 'Privacy Policy',
    submit: 'Send my enquiry',
    sending: 'Sending…',
    required: 'Please add your name and email, and agree to the data notice.',
    error: "We couldn't send your enquiry. Please try again shortly, or contact us by email or WhatsApp.",
    tooMany: 'Too many enquiries in a short time. Please try again later.',
    sentTitle: 'Thank you — your enquiry is in',
    sentBody: 'A planner will be in touch shortly. For anything urgent, message us on WhatsApp.',
    reference: 'Reference',
    another: 'Send another enquiry',
    airportCta: 'Airport VIP can be booked online today',
  },
};
